sudo: required
services:
  - docker

before_install:
  - docker build -t auaden/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run auaden/react-test npm run test -- --coverage

after_success:
  - docker build -t auaden/multi-client ./client
  - docker build -t auaden/multi-nginx ./nginx
  - docker build -t auaden/multi-worker ./worker
  - docker build -t auaden/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push auaden/multi-client
  - docker push auaden/multi-nginx
  - docker push auaden/multi-server
  - docker push auaden/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: 'ap-southeast-1'
#   app: 'docker-react'
#   env: 'DockerReact-env'
#   bucket_name: 'elasticbeanstalk-ap-southeast-1-037203025666'
#   path: 'docker-react'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: '$AWS_SECRET_KEY'
